/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * NH payment API
 * OpenAPI spec version: 0.0.1
 */

export interface RegisterRequest {
  /** Name of the user */
  name: string;
  /** Email address of the user */
  email: string;
  /** Password for the account */
  password: string;
}
